### ISSUE TITLE
ERROR: The remote server returned an error: (404) Not Found.

### ISSUE THREAD

**Issue by AbelThar** [AndreAugustoAAQ/chocolatey-packages#2]
I have the same issue that [was mentioned in the chocolatey package webpage here](http://disq.us/p/2ens691)

Looking at the issue a bit, [it might be this line](https://github.com/AndreAugustoAAQ/chocolatey-packages/blob/8f9d494277c903fd52b1ef4af7776dbbbcad7d19/kdeconnect-kde/Update.ps1#L4) where
```ps1
$artifacts64 = 'https://binary-factory.kde.org/view/Windows%2064-bit/job/kdeconnect-kde_Release_win64/lastSuccessfulBuild/artifact/'
```
needs to be changed to
```ps1
$artifacts64 = 'https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/lastSuccessfulBuild/artifact/'
```
I would do it myself but I'm not sure how to test it beforehand (I guess put a bit more effort, but a bit time limited for now, maybe would do it later)

**Comment by AndreAugustoAAQ** [comment]
Hello,
The artifacts64 line is used to obtain the current download url
This problem was corrected in the most recent commit, adding auto update and automatic push of the latest package using AppVeyor
For now the version accepted in the repository is out of date, however the latest version is awaiting review
See version history:
https://chocolatey.org/packages/kdeconnect-kde/#versionhistory
An update check is done daily at 00:00, and if it exists it is sent to the repository
Thank you for the warning!

**Comment by AbelThar** [comment]
Good to know its being dealt with. Appreciate the effort :)
I'll close the issue
