### ISSUE TITLE
kde connect link is broken

### ISSUE THREAD

**Issue by adrianinsaval** [AndreAugustoAAQ/chocolatey-packages#3]
https://github.com/AndreAugustoAAQ/chocolatey-packages/blob/e3a6acdb9473bb0a3ba88eccc533693b0662a879/kdeconnect-kde/tools/ChocolateyInstall.ps1#L3
This link no longer works as it's constantly being rebuild, a possible solution is how the kate and okular packages manage it:
https://gitlab.com/dimqua/choco/-/tree/stable/kate

**Comment by AndreAugustoAAQ** [comment]
Ignore this url, as the package is updated daily and sent to chocolatey using AppVeyor, and you can update the code by running update.ps1

**Comment by adrianinsaval** [comment]
@AndreAugustoAAQ sorry I attempted to install and the link was outdated so I asumed it was just that, now I see there is a newer version with the correct link, however the new versions don't seem to get aproval and one has to manually specify a version, wouldn't it be better to follow the approach of the other kde packages and upload the installer to chocolatey?

**Comment by AndreAugustoAAQ** [comment]
@adrianinsaval A moderator's review is required to be approved, which is why so many versions ago.
The package follows the same logic as other KDE packages, check the source code and you will see, I used the update code for the Okular package as a base.
Another point is that daily builds occur, which if I'm not mistaken do not happen in the apps mentioned
What happens is that only the version sent to the repository is updated with AppVeyor, and the code on GitHub remains the same
It would be necessary to implement an automation to perform the code update on GitHub
I will study how to implement this update in the repository
If you want or if you know how to do that, a PR is welcome

If installing the package by compiling the source, run Update.ps1 first and the download url will be updated to the latest version

Thanks for the collaboration :smile:
